### ISSUE TITLE
Gecko lib 3

### ISSUE THREAD

**Issue by TankTheCat** [Ladysnake/Pick-Your-Poison#24]
I don’t know whether this is a server issue or not but when I launch my server it crashes. The log says that I am missing a required dependency which in this case is something called gecko lib 3. I have tried searching on the internet for it but all that comes up is the normal gecko lib. On the dependencies page when you download gecko it is a forge version and that does not work either. I have tried using both fabric and quilt and I can’t get any results.

**Comment by TankTheCat** [comment]
If you need a reference of the crash here is a link to the report using quilt: https://mclo.gs/wObYlEc

**Comment by Xiribidus** [comment]
Geckolib3 is indeed just the regular geckolib, a quilt version can be found [here](https://www.curseforge.com/minecraft/mc-mods/geckolib/files).

It seems you are also using FAPI on quilt? You should replace that with [QSL](https://www.curseforge.com/minecraft/mc-mods/qsl).

You are also using some 1.19.2 mods which will not work on 1.19.4, so if you want to use all those mods you will probably have to downgrade the minecraft version to 1.19.2.

**Comment by Stehlampe2020** [comment]
> Geckolib3 is indeed just the regular geckolib

When I installed the fabric version of geckolib on fabric 1.19.4 the game just crashed saying I need to install geckolib3...

**Comment by Xiribidus** [comment]
Please send a pastebin link or smth similar to the crash log

**Comment by Stehlampe2020** [comment]
The `latest.log` contains the following after trying to start with `geckolib` and `pickyourpoison`: 
```
[17:06:12] [main/INFO]: Loading Minecraft 1.19.4 with Fabric Loader 0.14.19
[17:06:12] [main/WARN]: Mod resolution failed
[17:06:12] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE pickyourpoison 1.0.11 {depends geckolib3 @ [*]}, ROOT_FORCELOAD_SINGLE pickyourpoison 1.0.11]
[17:06:12] [main/INFO]: Reason: [HARD_DEP pickyourpoison 1.0.11 {depends geckolib3 @ [*]}]
[17:06:12] [main/INFO]: Fix: add [add:geckolib3 1 ([(-∞,∞)])], remove [], replace []
[17:06:12] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install geckolib3, any version.
Unmet dependency listing:
	 - Mod 'Pick Your Poison' (pickyourpoison) 1.0.11 requires any version of geckolib3, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
```

**Comment by Xiribidus** [comment]
Pick your Poison is for 1.19.2, 1.19.2 mods are not compatible with 1.19.3 or .4, on the geckolib part what version exactly were you using?

**Comment by Stehlampe2020** [comment]
I used the fabric 1.19.4 version of `geckolib`.

**Comment by Nadelio** [comment]
> > Geckolib3 is indeed just the regular geckolib
> 
> When I installed the fabric version of geckolib on fabric 1.19.4 the game just crashed saying I need to install geckolib3...

Same, I'm about to quit because I just don't know how to get this to work...

**Comment by Xiribidus** [comment]
Again, PYP is for 1.19.2 and won't work on 1.19.4
